version: '2.0'

services:
    analise:
        container_name: analise
        image: colares07/docker-tcc-analise
        environment:
            QUEUE_HOST: rabbitmq
            DATABASE_HOST: mongo
        networks: 
            - rabbitmq-network
            - db-nosql-network 

networks:
    rabbitmq-network:
        name: rabbitmq-network
        external: true

    db-nosql-network:
        name: db-nosql-network 
        external: true