version: '3.5'
services: 
     
    eureka-server:
        container_name: eureka-server
        image: colares07/spring-boot-tcc-eureka
        ports: 
            - "8800:8800"
        networks:
          - api-network

    paciente:
        container_name: paciente
        image: colares07/spring-boot-tcc-paciente
        environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/tcc-db

          - SPRING_DATASOURCE_HOST=localhost
          - SPRING_DATASOURCE_PORT=3306

          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=root2020!
          - EUREKA_URL=http://localhost:8800/eureka
        ports:
            - "8050:8050"
        links:
          - eureka-server
        depends_on:
          - eureka-server
        networks:
          - api-network

    exame:
        container_name: exame
        image: colares07/spring-boot-tcc-exame
        environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/tcc-db

          - SPRING_DATASOURCE_HOST=localhost
          - SPRING_DATASOURCE_PORT=3306

          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=root2020!
          
          - EUREKA_URL=http://localhost:8800/eureka

          - SPRING_DATA_MONGO_TYPE_AUTHENTICATION=admin
          - SPRING_DATA_MONGO_DATABASE=tcc-db
          - SPRING_DATA_MONGO_HOST=localhost
          - SPRING_DATA_MONGO_PASSWORD=MongoDB2019!
          - SPRING_DATA_MONGO_PORT=27017
          - SPRING_DATA_MONGO_USERNAME=root

        ports:
            - "8060:8060"
        links:
          - eureka-server
        depends_on:
          - eureka-server
        networks:
          - api-network
    
    medico:
        container_name: medico
        image: colares07/spring-boot-tcc-medico
        environment:
          - EUREKA_URL=http://localhost:8800/eureka
        ports:
            - "8055:8055"
        links:
          - eureka-server
        depends_on:
          - eureka-server
        networks:
          - api-network

    tecnico:
        container_name: tecnico
        image: colares07/spring-boot-tcc-tecnico
        environment:        
          - EUREKA_URL=http://localhost:8800/eureka
        ports:
            - "8070:8070"
        links:
          - eureka-server
        depends_on:
          - eureka-server
        networks:
          - api-network

    retorno:
        container_name: retorno
        image: colares07/spring-boot-tcc-retorno
        environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/tcc-db

          - SPRING_DATASOURCE_HOST=localhost
          - SPRING_DATASOURCE_PORT=3306

          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=root2020!
          
          - EUREKA_URL=http://localhost:8800/eureka
        ports:
            - "8099:8099"
        links:
          - eureka-server
          - fila-analise
        depends_on:
          - eureka-server
          - fila-analise
        networks:
          - api-network

    fila-consolidado:
        container_name: fila-consolidado
        image: colares07/spring-boot-tcc-consolidar-analise
        environment:
          - SPRING_RABBITMQ_HOST=localhost
          - SPRING_RABBITMQ_PASSWORD=guest
          - SPRING_RABBITMQ_PORT=5672
          - SPRING_RABBITMQ_USERNAME=guest

          - QUEUE.NAME=fila.consolidar.exame

          - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/tcc-db

          - SPRING_DATASOURCE_HOST=localhost
          - SPRING_DATASOURCE_PORT=3306
          
          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=root2020!

          - SPRING_DATA_MONGO_TYPE_AUTHENTICATION=admin
          - SPRING_DATA_MONGO_DATABASE=tcc-db
          - SPRING_DATA_MONGO_HOST=localhost
          - SPRING_DATA_MONGO_PASSWORD=MongoDB2019!
          - SPRING_DATA_MONGO_PORT=27017
          - SPRING_DATA_MONGO_USERNAME=root 
        networks:
          - api-network


    fila-analise:
        container_name: fila-analise
        image: colares07/spring-boot-tcc-fila-analise
        environment:
          - SPRING_RABBITMQ_HOST=localhost
          - SPRING_RABBITMQ_PASSWORD=guest
          - SPRING_RABBITMQ_PORT=5672
          - SPRING_RABBITMQ_USERNAME=guest

          - QUEUE.NAME=fila.analise.exame

          - EUREKA_URL=http://localhost:8800/eureka
        links:
          - eureka-server
        depends_on:
          - eureka-server
        networks:
          - api-network

networks:
    api-network:
#         name: api-network
#         external: true