version: '3.5'
services: 
     
    eureka-server:
        container_name: eureka-server
        image: tccbigdata/spring-boot-tcc-eureka:1.0.0
        ports: 
            - "8800:8800"
        networks:
          - api-network

    paciente:
        container_name: paciente
        image: tccbigdata/spring-boot-tcc-paciente:1.0.0
        environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/tcc-db

          - SPRING_DATASOURCE_HOST=db-mysql
          - SPRING_DATASOURCE_PORT=3306

          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=root2020!
          - EUREKA_URL=http://eureka-server:8800/eureka
        ports:
            - "8050:8050"
        links:
          - eureka-server
        depends_on:
          - eureka-server
        networks:
          - api-network
          - db-sql-network

    exame:
        container_name: exame
        image: tccbigdata/spring-boot-tcc-exame:1.0.0
        environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/tcc-db

          - SPRING_DATASOURCE_HOST=db-mysql
          - SPRING_DATASOURCE_PORT=3306

          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=root2020!
          
          - EUREKA_URL=http://eureka-server:8800/eureka

          - SPRING_DATA_MONGO_TYPE_AUTHENTICATION=admin
          - SPRING_DATA_MONGO_DATABASE=tcc-db
          - SPRING_DATA_MONGO_HOST=db-mongo
          - SPRING_DATA_MONGO_PASSWORD=MongoDB2019!
          - SPRING_DATA_MONGO_PORT=27017
          - SPRING_DATA_MONGO_USERNAME=root

        ports:
            - "8060:8060"
        links:
          - eureka-server

        depends_on:
          - eureka-server
        networks:
          - api-network
          - db-nosql-network
          - db-sql-network
    
    medico:
        container_name: medico
        image: tccbigdata/spring-boot-tcc-medico:1.0.0
        environment:
          - EUREKA_URL=http://eureka-server:8800/eureka
        ports:
            - "8055:8055"
        links:
          - eureka-server
        depends_on:
          - eureka-server
        networks:
          - api-network

    tecnico:
        container_name: tecnico
        image: tccbigdata/spring-boot-tcc-tecnico:1.0.0
        environment:        
          - EUREKA_URL=http://eureka-server:8800/eureka
        ports:
            - "8070:8070"
        links:
          - eureka-server
        depends_on:
          - eureka-server
        networks:
          - api-network

    retorno:
        container_name: retorno
        image: tccbigdata/spring-boot-tcc-retorno:1.0.0
        environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/tcc-db

          - SPRING_DATASOURCE_HOST=db-mysql
          - SPRING_DATASOURCE_PORT=3306

          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=root2020!
          
          - EUREKA_URL=http://eureka-server:8800/eureka
        ports:
            - "8099:8099"
        links:
          - eureka-server
          - fila-analise
        depends_on:
          - eureka-server
          - fila-analise
        networks:
          - api-network
          - db-sql-network

    fila-consolidado:
        container_name: fila-consolidado
        image: tccbigdata/spring-boot-tcc-consolidar-analise:1.0.0
        environment:
          - SPRING_RABBITMQ_HOST=rabbitmq
          - SPRING_RABBITMQ_PASSWORD=guest
          - SPRING_RABBITMQ_PORT=5672
          - SPRING_RABBITMQ_USERNAME=guest

          - QUEUE.NAME=fila.consolidar.exame

          - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/tcc-db

          - SPRING_DATASOURCE_HOST=db-mysql
          - SPRING_DATASOURCE_PORT=3306
          
          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=root2020!

          - SPRING_DATA_MONGO_TYPE_AUTHENTICATION=admin
          - SPRING_DATA_MONGO_DATABASE=tcc-db
          - SPRING_DATA_MONGO_HOST=db-mongo
          - SPRING_DATA_MONGO_PASSWORD=MongoDB2019!
          - SPRING_DATA_MONGO_PORT=27017
          - SPRING_DATA_MONGO_USERNAME=root 
        networks:
          - api-network
          - rabbitmq-network
          - db-nosql-network
          - db-sql-network


    fila-analise:
        container_name: fila-analise
        image: tccbigdata/spring-boot-tcc-fila-analise:1.0.0
        environment:
          - SPRING_RABBITMQ_HOST=rabbitmq
          - SPRING_RABBITMQ_PASSWORD=guest
          - SPRING_RABBITMQ_PORT=5672
          - SPRING_RABBITMQ_USERNAME=guest

          - QUEUE.NAME=fila.analise.exame

          - EUREKA_URL=http://eureka-server:8800/eureka
        links:
          - eureka-server
        depends_on:
          - eureka-server
        networks:
          - api-network
          - rabbitmq-network

networks:
    api-network:
#         name: api-network
#         external: true

    rabbitmq-network:
        name: rabbitmq-network
        external: true

    db-nosql-network:
        name: db-nosql-network 
        external: true

    db-sql-network:
        name: db-sql-network 
        driver: bridge
        external: false